name: Dependency check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install pipenv
        run: |
          pip3 install pipenv
      - name: Check dependencies
        run: |
          pipenv sync --dev
          pipenv check
