name: Dependency check

on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install pipenv
        run: |
          easy_install3 --upgrade pip
          pip3 install pipenv
      - name: Check dependencies
        run: |
          pipenv shell
          pipenv sync --dev
          pipenv check
