name: Lint

on: [ push ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run flake8
        uses: TrueBrain/actions-flake8@master
