name: Lint

on:
  pull_request:
      branches:
        - master
  push:
      branches:
        - master

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run flake8
        uses: TrueBrain/actions-flake8@master
